version: "3"
services:
  silserver:
    image: python:3.7
    volumes:
      - ./python:/scripts:ro
      - ./log/uwsgi:/log/uwsgi
    environment:
      TZ: Asia/Tokyo
    restart: always
    command: >
      /bin/bash -c "
      git clone -b impl-v0.1.0 https://github.com/cordx56/silang.git /silang &&
      cd /silang &&
      make DEBUG= &&
      cd /scripts &&
      pip install pipenv &&
      pipenv install --system &&
      uwsgi --enable-threads --ini /scripts/uwsgi.ini"
  nginxserver:
    image: nginx:1.17
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./log/nginx:/var/log/nginx
      - ./vue:/vue:ro
    links:
      - silserver
    ports:
      - 8005:80
    environment:
      TZ: Asia/Tokyo
    restart: always
  htmlBuilder:
    image: node:12
    volumes:
      - ./vue:/scripts
    command: >
      /bin/bash -c "
      cd /scripts &&
      npm clean-install &&
      npm run build"
