version: "3"
services:
  silserver:
    build: python
    volumes:
      - ./log/gunicorn:/log/gunicorn
    environment:
      TZ: Asia/Tokyo
    restart: always
  vue:
    build: vue
    volumes:
      - ./log/nginx:/var/log/nginx
    ports:
      - 8005:80
    environment:
      TZ: Asia/Tokyo
    restart: always
